[formatter]
indentStyle = "space"
indentWidth = 2
lineEnding = "lf"
lineWidth = 100

[ linter ]
enabled = true

[javascript.formatter]
quoteStyle = "double"
trailingCommas = "none"

[files]
ignores = ["node_modules/", "dist/", "bun.lock", ".workbuddy-ai/"]
