/**
 * Shell layout dimensions. Single source of truth so the AppShell navbar
 * width, the rail column and the collapse toggle all agree.
 */
export const LAYOUT = {
  /** Narrow launcher/action rail (outermost full-height column). */
  railWidth: 60,
  /** Page-tree pane width when expanded. */
  treePaneWidth: 336
} as const

export const UI_TEXT = {
  appName: 'RTWiki',
  description: 'A personal knowledge workspace for your family. Offline, private, and portable.',
  ready: 'RTWiki is ready',
  readyHint: 'The application is connected to the backend. Content editing will be available soon.',
  connectionFailed: 'The backend server is not responding. Make sure the application is running.',
  retry: 'Retry',
  dashboardTitle: 'Pages',
  emptyTitle: 'No pages yet',
  emptyDescription: 'Create your first page to get started.',
  createRichNote: 'Create Rich Note',
  createHtmlPage: 'Create HTML Page',
  richNote: 'Rich Note',
  htmlPage: 'HTML Page',
  searchPlaceholder: 'Search pages...',
  searchLabel: 'Search pages',
  newPageTitle: 'New page',
  titleLabel: 'Title',
  titlePlaceholder: 'Enter page title',
  titleRequired: 'Title is required',
  titleTooLong: 'Title must be 200 characters or fewer',
  typeLabel: 'Page type',
  createButton: 'Create',
  cancelButton: 'Cancel',
  saveStatusSaving: 'Saving...',
  saveStatusSaved: 'Saved',
  saveStatusError: 'Save failed',
  saveStatusRetry: 'Retry',
  untitledPage: 'Untitled',
  renameAction: 'Rename',
  duplicateAction: 'Duplicate',
  deleteAction: 'Delete',
  deleteTitle: 'Delete page',
  deleteConfirmation: 'Are you sure you want to delete this page? This action cannot be undone.',
  deleteButton: 'Delete',
  errorLoadingPages: 'Failed to load pages.',
  errorCreatingPage: 'Failed to create page.',
  errorDeletingPage: 'Failed to delete page.',
  errorDuplicatingPage: 'Failed to duplicate page.',
  errorRenamingPage: 'Failed to rename page.',
  themeToggleLabel: 'Toggle color scheme',
  sidebarNewPage: 'New page',
  noResults: 'No pages match your search.',
  loadingPages: 'Loading pages...',
  editorPlaceholderTitle: 'Page title',
  editorPlaceholderContent: 'Editor coming in Phase 3 — title and page actions are active now.',
  backToDashboard: 'Back to pages',
  stopRtwiki: 'Stop RTWiki',
  stopConfirmTitle: 'Stop RTWiki',
  stopConfirmMessage: 'This will shut down the RTWiki server. Any unsaved changes may be lost.',
  stopButton: 'Stop',
  stopSuccessMessage: 'RTWiki has stopped. You may close this browser tab.',
  stopError: 'Failed to stop RTWiki.',
  utilityRailHome: 'Home',
  utilityRailSearch: 'Search',
  utilityRailNewPage: 'New page',
  utilityRailTheme: 'Theme',
  utilityRailStop: 'Stop RTWiki',
  activePageTabLabel: 'Active page',
  closeTabLabel: 'Close and return to dashboard',
  htmlPlaceholderTitle: 'HTML / CSS / JavaScript editor',
  htmlPlaceholderMessage:
    'The HTML/CSS/JS editor is coming in the next phase. Your HTML pages are safely stored and will be editable soon.',
  htmlPlaceholderHint: 'HTML pages remain viewable as stored content.',
  htmlPreviewIframeTitle: 'Sandboxed HTML page preview',
  htmlPreviewErrorTitle: 'Preview unavailable',
  htmlPreviewNonceMissing:
    'The preview could not start because this document was served without a security nonce. Reload the application and try again.',
  htmlPreviewBuildFailed: 'The preview could not be built from the stored content.',
  htmlPreviewPreservedNotice:
    'Your stored page content is untouched. Nothing was modified or deleted.',
  htmlPreviewRuntimeTitle: 'The preview reported a problem',
  htmlPreviewRuntimeMessage:
    'Code inside the sandboxed preview stopped unexpectedly. The rest of RTWiki is unaffected.',
  editorTabsLabel: 'HTML page editors',
  editorTabHtml: 'HTML',
  editorTabCss: 'CSS',
  editorTabJs: 'JavaScript',
  editorPaneLabelHtml: 'HTML source editor',
  editorPaneLabelCss: 'CSS source editor',
  editorPaneLabelJs: 'JavaScript source editor',
  jsEnabledToggleLabel: 'Enable JavaScript in preview',
  htmlEditorLoadError:
    'This HTML page could not be loaded. The stored content appears to be corrupted.',
  htmlEditorCrashMessage: 'The HTML editor stopped unexpectedly.',
  htmlEditorLoadingLabel: 'Loading the HTML editor…',
  richEditorLoadError:
    'This Rich Note could not be loaded. The stored content appears to be corrupted.',
  richEditorCrashTitle: 'The editor encountered a problem',
  richEditorCrashMessage: 'The rich text editor stopped unexpectedly. Your saved content is safe.',
  richEditorPreserveNotice:
    'Original content has been preserved. Reset the document to start fresh.',
  richEditorResetButton: 'Reset document',
  richEditorLogLocation: 'Technical details are written to logs\\rtwiki.log',
  richEditorReferenceLabel: 'Diagnostic reference',
  appCrashTitle: 'Something went wrong',
  appCrashMessage: 'The application hit an unexpected problem. Reload to continue.',
  appCrashReload: 'Reload RTWiki',
  newChildRichPage: 'New child Rich Note',
  newChildHtmlPage: 'New child HTML Page',
  newRichPage: 'New Rich Note',
  newHtmlRootPage: 'New HTML Page',
  htmlSourceBackToPreview: 'Return to preview',
  htmlPreviewEmpty:
    'This page has no content yet. Open HTML, CSS or JavaScript from the tree to start writing.',
  openAction: 'Open',
  moveToLabel: 'Move',
  moveUpLabel: 'Move up',
  moveDownLabel: 'Move down',
  moveToParentLabel: 'Move to parent page',
  hierarchyFutureNote: 'Hierarchical page organization is planned for a future release.',
  saveFailedRetryHint: 'Save failed. You can retry or keep editing.',
  unsavedChangesWarning:
    'You have unsaved changes that failed to save. Please retry before leaving or your recent edits may be lost.',
  abruptExitNotice:
    'If the browser or app is closed abruptly, only the current unsaved debounce window may be lost.',
  // Workspace tabs
  tabStripLabel: 'Open pages',
  tabCloseLabel: 'Close tab',
  // Shell navigation
  toggleNavigation: 'Toggle navigation',
  collapseTreeLabel: 'Collapse page tree',
  expandTreeLabel: 'Expand page tree',
  // Rich Document toolbar
  richToolbarLabel: 'Formatting',
  undoLabel: 'Undo',
  redoLabel: 'Redo',
  paragraphLabel: 'Paragraph',
  headingLabel: 'Heading',
  boldLabel: 'Bold',
  italicLabel: 'Italic',
  underlineLabel: 'Underline',
  strikeLabel: 'Strikethrough',
  textColorLabel: 'Text colour',
  highlightLabel: 'Highlight',
  checklistLabel: 'Checklist',
  alignLeft: 'Align left',
  alignCenter: 'Align centre',
  alignRight: 'Align right',
  indentLabel: 'Indent',
  outdentLabel: 'Outdent',
  quoteLabel: 'Quote block',
  codeBlockLabel: 'Code block',
  tableLabel: 'Insert table',
  clearFormattingLabel: 'Clear formatting',
  bulletListLabel: 'Bulleted list',
  numberedListLabel: 'Numbered list',
  linkLabel: 'Link',
  linkApply: 'Apply link',
  richPlaceholder: 'Type here…',
  // Right sidebar
  rightSidebarLabel: 'Page details',
  collapseSidebarLabel: 'Collapse sidebar',
  outlineTitle: 'Outline',
  outlineEmpty: 'No headings yet. Add a heading to build the outline.',
  pageInfoTitle: 'Page info',
  pageInfoType: 'Type',
  pageInfoCreated: 'Created',
  pageInfoUpdated: 'Modified',
  // Visual knowledge blocks
  insertMenuLabel: 'Insert',
  formulaLabel: 'Formula',
  diagramLabel: 'Diagram',
  mindMapLabel: 'Mind map',
  calloutLabel: 'Callout',
  calloutInfoLabel: 'Info callout',
  calloutNoteLabel: 'Note callout',
  calloutTipLabel: 'Tip callout',
  calloutWarningLabel: 'Warning callout',
  calloutDangerLabel: 'Danger callout',
  diagramEditLabel: 'Edit source',
  diagramApplyLabel: 'Apply',
  diagramErrorTitle: 'Diagram error',
  diagramRetryLabel: 'Retry render',
  // Settings / diagnostics
  settingsLabel: 'Settings',
  debugToggleLabel: 'Debug logging',
  debugToggleDescription:
    'Writes technical diagnostics to logs\\rtwiki-debug.jsonl. Never records note content.',
  debugActiveLabel: 'Debug logging is active',
  // HTML preview actions
  refreshPreviewLabel: 'Refresh preview',
  previewRefreshingLabel: 'Refreshing preview…',
  jsSandboxHint:
    'Scripts run only inside an isolated sandboxed frame. They cannot access RTWiki data or the network.'
} as const

export const STATUS_TEXT = {
  description: UI_TEXT.description,
  ready: UI_TEXT.ready,
  readyHint: UI_TEXT.readyHint,
  connectionFailed: UI_TEXT.connectionFailed,
  retry: UI_TEXT.retry
} as const
