export const UI_TEXT = {
  appName: 'RTWiki',
  description: 'A personal knowledge workspace for your family. Offline, private, and portable.',
  ready: 'RTWiki is ready',
  readyHint: 'The application is connected to the backend. Content editing will be available soon.',
  connectionFailed: 'The backend server is not responding. Make sure the application is running.',
  retry: 'Retry',
  dashboardTitle: 'Pages',
  emptyTitle: 'No pages yet',
  emptyDescription: 'Create your first page to get started.',
  createRichNote: 'Create Rich Note',
  createHtmlPage: 'Create HTML Page',
  richNote: 'Rich Note',
  htmlPage: 'HTML Page',
  searchPlaceholder: 'Search pages...',
  searchLabel: 'Search pages',
  newPageTitle: 'New page',
  titleLabel: 'Title',
  titlePlaceholder: 'Enter page title',
  titleRequired: 'Title is required',
  titleTooLong: 'Title must be 200 characters or fewer',
  typeLabel: 'Page type',
  createButton: 'Create',
  cancelButton: 'Cancel',
  saveStatusSaving: 'Saving...',
  saveStatusSaved: 'Saved',
  saveStatusError: 'Save failed',
  untitledPage: 'Untitled',
  renameAction: 'Rename',
  duplicateAction: 'Duplicate',
  deleteAction: 'Delete',
  deleteTitle: 'Delete page',
  deleteConfirmation: 'Are you sure you want to delete this page? This action cannot be undone.',
  deleteButton: 'Delete',
  errorLoadingPages: 'Failed to load pages.',
  errorCreatingPage: 'Failed to create page.',
  errorDeletingPage: 'Failed to delete page.',
  errorDuplicatingPage: 'Failed to duplicate page.',
  errorRenamingPage: 'Failed to rename page.',
  themeToggleLabel: 'Toggle color scheme',
  sidebarNewPage: 'New page',
  noResults: 'No pages match your search.',
  loadingPages: 'Loading pages...',
  editorPlaceholderTitle: 'Page title',
  editorPlaceholderContent: 'Editor coming in Phase 3 — title and page actions are active now.',
  backToDashboard: 'Back to pages'
} as const

export const STATUS_TEXT = {
  description: UI_TEXT.description,
  ready: UI_TEXT.ready,
  readyHint: UI_TEXT.readyHint,
  connectionFailed: UI_TEXT.connectionFailed,
  retry: UI_TEXT.retry
} as const
